CREATE DATABASE IF NOT EXISTS LoteriaDB;

use LoteriaDB;

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';

CREATE TABLE `tconfiguracion` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `PROPIEDAD` varchar(400) NOT NULL,
  `VALOR` varchar(400) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tsorteoestado` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `SORTEO_ID` int NOT NULL,
  `CHANCE` varchar(2) NOT NULL,
  `CANTIDAD` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1202 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tsorteos` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` int NOT NULL,
  `NOMBRE` varchar(500) DEFAULT NULL,
  `FECHA` datetime DEFAULT NULL,
  `ESACTIVO` enum('SI','NO') DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tsorteotiquetes` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `SORTEO_ID` int NOT NULL,
  `TIPO` enum('CHANCE','BILLETE') DEFAULT NULL,
  `FECHA` datetime DEFAULT NULL,
  `VENDEDOR_ID` int NOT NULL,
  `GANADOR` enum('SI','NO') DEFAULT NULL,
  `VALOR` double NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tsorteotiquetesregistros` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TIQUETE_ID` int NOT NULL,
  `NUMERO` varchar(6) NOT NULL,
  `CANTIDAD` int NOT NULL,
  `PRECIO` double DEFAULT NULL,
  `VALOR` double NOT NULL,
  `GANADOR` enum('SI','NO') DEFAULT NULL,
  `PRIMER_PREMIO` enum('CHANCE_GANADOR','CUATRO_NUMEROS','TRES_PRIMEROS','TRES_ULTIMOS','DOS_PRIMEROS','DOS_ULTIMOS','ULTIMO_NUMERO') DEFAULT NULL,
  `SEGUNDO_PREMIO` enum('CHANCE_GANADOR','CUATRO_NUMEROS','TRES_PRIMEROS','TRES_ULTIMOS','DOS_ULTIMOS') DEFAULT NULL,
  `TERCER_PREMIO` enum('CHANCE_GANADOR','CUATRO_NUMEROS','TRES_PRIMEROS','TRES_ULTIMOS','DOS_ULTIMOS') DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=162 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tusuarios` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(20) NOT NULL,
  `CONTRASENA` varchar(20) NOT NULL,
  `PERFIL` enum('ADMIN','VENDEDOR') DEFAULT NULL,
  `ESACTIVO` enum('SI','NO') DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;







