CREATE DEFINER=`root`@`localhost` PROCEDURE `rActualizaGanadores1erPremio`(
    IN _SORTEO INT,
    IN _PREMIO VARCHAR(13),    
    IN _BILLETE VARCHAR(400),
    IN _INICIO INT,
    IN _LONGITUD INT)
BEGIN
	DECLARE PREMIO enum('CHANCE_GANADOR','CUATRO_NUMEROS','TRES_PRIMEROS','TRES_ULTIMOS','DOS_PRIMEROS','DOS_ULTIMOS','ULTIMO_NUMERO');
    SET PREMIO = _PREMIO;
    SET SQL_SAFE_UPDATES = 0;    
    
    /*Buscar números*/    
    UPDATE tsorteotiquetes TIQ
	LEFT JOIN tSorteoTiquetesRegistros REG on TIQ.ID = REG.TIQUETE_ID    
    SET TIQ.GANADOR = 'SI', REG.PRIMER_PREMIO = PREMIO, REG.GANADOR = 'SI'
	WHERE TIQ.TIPO = 'BILLETE'
    AND TIQ.SORTEO_ID = _SORTEO
	AND  SUBSTR(REG.NUMERO,_INICIO,_LONGITUD) = _BILLETE;    
    
	END