CREATE DEFINER=`root`@`localhost` PROCEDURE `rActualizaCantidadChance`(
IN _SORTEO_ID INT,
IN _CHANCE VARCHAR(2),
IN _CANTIDAD INT
)
BEGIN
DECLARE CANTIDAD_ACTUAL INT;
SET SQL_SAFE_UPDATES = 0;

SELECT @CANTIDAD_ACTUAL := CANTIDAD FROM tSorteoEstado
WHERE SORTEO_ID = _SORTEO_ID AND CHANCE = _CHANCE;

UPDATE tSorteoEstado SET CANTIDAD = @CANTIDAD_ACTUAL + _CANTIDAD 
WHERE SORTEO_ID = _SORTEO_ID AND CHANCE = _CHANCE;

SELECT CHANCE, CANTIDAD FROM tSorteoEstado
WHERE SORTEO_ID = _SORTEO_ID AND CHANCE = _CHANCE;
END