CREATE DEFINER=`root`@`localhost` PROCEDURE `rActualizaConfiguracion`(
    IN _NOMBRE VARCHAR(400),
    IN _CHANCE VARCHAR(400),
    IN _BILLETE VARCHAR(400),
    IN _TAMANO VARCHAR(400),
    IN _SORTEO VARCHAR(400)
    )
BEGIN
	DECLARE _NOMBRE_SORTEO VARCHAR(400);
    SET SQL_SAFE_UPDATES = 0;
    UPDATE tConfiguracion SET VALOR = _NOMBRE WHERE PROPIEDAD = "NOMBRE";
    UPDATE tConfiguracion SET VALOR = _CHANCE WHERE PROPIEDAD = "PRECIO_CHANCE";
    UPDATE tConfiguracion SET VALOR = _BILLETE WHERE PROPIEDAD = "PRECIO_BILLETE";
    UPDATE tConfiguracion SET VALOR = _TAMANO WHERE PROPIEDAD = "IMPRESION_TAMANO";	    
    UPDATE tConfiguracion SET VALOR = _SORTEO WHERE PROPIEDAD = "SORTEO_VENTA";
    END