CREATE DEFINER=`root`@`localhost` PROCEDURE `rAgregarRegistros`(
IN _TIQUETE_ID INT,
IN _NUMERO VARCHAR(6),
IN _CANTIDAD INT,
IN _VALOR DOUBLE,
IN _PRECIO DOUBLE
)
BEGIN
INSERT INTO tSorteoTiquetesRegistros (TIQUETE_ID, NUMERO, CANTIDAD, PRECIO, VALOR, GANADOR)
VALUES (_TIQUETE_ID, _NUMERO, _CANTIDAD, _PRECIO, _VALOR, "NO");
END