CREATE DEFINER=`root`@`localhost` PROCEDURE `rCierraSorteo`(
IN _SORTEO_ID INT
)
BEGIN

SET SQL_SAFE_UPDATES = 0;


UPDATE tSorteos SET ESACTIVO = "NO"
WHERE ID = _SORTEO_ID;

SELECT ID,NOMBRE,ESACTIVO FROM tSorteos
WHERE ID = _SORTEO_ID;
END