CREATE DEFINER=`root`@`localhost` PROCEDURE `rCrearTiquete`(
IN _SORTEO_ID INT,
IN _USUARIO_ID INT,
IN _TIPO VARCHAR(8),
IN _VALOR DOUBLE
)
BEGIN
INSERT INTO tSorteoTiquetes (SORTEO_ID, TIPO, FECHA, VENDEDOR_ID, GANADOR, VALOR)
VALUES (_SORTEO_ID, _TIPO, SYSDATE(),_USUARIO_ID, "NO",_VALOR);

SELECT LAST_INSERT_ID() AS TIQUETE_ID;
END