CREATE DEFINER=`root`@`localhost` PROCEDURE `rCrearSorteo`(
	IN _USUARIO INT,
    IN _NOMBRE VARCHAR(500)
    )
BEGIN
	DECLARE NUMERO_SORTEO INT;
    DECLARE NUMERO INT;
    DECLARE USUARIO INT
	INSERT INTO tSorteos (USUARIO_ID, NOMBRE, FECHA, ESACTIVO) VALUES(_USUARIO, _NOMBRE, SYSDATE(), "SI");    
    SET NUMERO_SORTEO = LAST_INSERT_ID();
    SET NUMERO = 0;
    SET USUARIO = 1;
	creandoChanceBase: LOOP
		INSERT INTO tSorteoEstado (SORTEO_ID, CHANCE)
		VALUES (NUMERO_SORTEO,LPAD(NUMERO,2,"00"));
    SET NUMERO = NUMERO + 1;
    
    IF NUMERO > 99 THEN
		SET NUMERO = 0;
        SET USUARIO = USUARIO + 1;
	END IF;
    
    IF USUARIO > 11 THEN
		LEAVE creandoChanceBase;
	END IF;
	END LOOP creandoChanceBase;  
END