use loteriadb;

CREATE TABLE tSorteos(
ID int not null auto_increment, 
USUARIO_ID INT NOT NULL,
NOMBRE VARCHAR(500),
FECHA DATETIME, 
ESACTIVO ENUM("SI","NO"),
PRIMARY KEY(ID)
);

CREATE TABLE tSorteoTiquetes(
ID INT NOT NULL auto_increment, 
SORTEO_ID INT NOT NULL,
TIPO ENUM("CHANCE","BILLETE"),
FECHA DATETIME,
VENDEDOR_ID INT NOT NULL,
GANADOR ENUM("SI","NO"),
VALOR double NOT NULL,
primary key(ID));

CREATE TABLE tSorteoTiquetesRegistros(
ID INT NOT NULL auto_increment, 
TIQUETE_ID INT NOT NULL,
NUMERO VARCHAR(6) NOT NULL,
CANTIDAD INT NOT NULL,
VALOR double NOT NULL,
GANADOR ENUM("SI","NO"),
PRIMER_PREMIO ENUM("CHANCE_GANADOR","CUATRO_NUMEROS","TRES_PRIMEROS","TRES_ULTIMOS","DOS_PRIMEROS","DOS_ULTIMOS","ULTIMO_NUMERO"),
SEGUNDO_PREMIO ENUM("CHANCE_GANADOR","CUATRO_NUMEROS","TRES_PRIMEROS","TRES_ULTIMOS","DOS_ULTIMOS"),
TERCER_PREMIO ENUM("CHANCE_GANADOR","CUATRO_NUMEROS","TRES_PRIMEROS","TRES_ULTIMOS","DOS_ULTIMOS"),
primary key(ID));

CREATE TABLE tSorteoEstado(
ID int not null auto_increment,
SORTEO_ID INT NOT NULL,
CHANCE VARCHAR(2) NOT NULL,
CANTIDAD INT NOT NULL DEFAULT 0,
primary key(ID)
);

CREATE TABLE tUsuarios(
ID INT NOT NULL auto_increment,
NOMBRE VARCHAR(20) NOT NULL,
CONTRASENA VARCHAR(20) NOT NULL,
PERFIL ENUM("ADMIN","VENDEDOR"),
ESACTIVO ENUM("SI","NO"),
PRIMARY KEY(ID)
);